// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gnongxogplcxvjemkvhq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdub25neG9ncGxjeHZqZW1rdmhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNzMwMTYsImV4cCI6MjA1OTk0OTAxNn0.y_Xg680s6mTwB3uNf5YzCclbFDJp7xyQwNHwxht0sJk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);